# Exercises

## Using the data/parsed.csv file and the material from this chapter, complete the following exercises to practice your pandas skills:

### Set up

We will be working with the `exercise/parsed.csv`

In [58]:
import pandas as pd
import numpy as np

df = pd.read_csv("parsed.csv")
df.head(2)

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9332 entries, 0 to 9331
Data columns (total 27 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   alert         59 non-null     object
 1   cdi           329 non-null    float64
 2   code          9332 non-null   object
 3   detail        9332 non-null   object
 4   dmin          6139 non-null   float64
 5   felt          329 non-null    float64
 6   gap           6164 non-null   float64
 7   ids           9332 non-null   object
 8   mag           9331 non-null   float64
 9   magType       9331 non-null   object
 10  mmi           93 non-null     float64
 11  net           9332 non-null   object
 12  nst           5364 non-null   float64
 13  place         9332 non-null   object
 14  rms           9332 non-null   float64
 15  sig           9332 non-null   int64
 16  sources       9332 non-null   object
 17  status        9332 non-null   object
 18  time          9332 non-null   int64
 19  title         9332 non-null   object
 20  tsunami       9332 non-null   int64
 21  type          9332 non-null   object
 22  types         9332 non-null   object
 23  tz            9331 non-null   float64
 24  updated       9332 non-null   int64
 25  url           9332 non-null   object
 26  parsed_place  9332 non-null   object
dtypes: float64(9), int64(4), object(14)
memory usage: 1.9+ MB

In [60]:
df.describe(include="all")

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
count,59,329.000000,9332,9332,6139.000000,329.000000,6164.000000,9332,9331.000000,9331,...,9332,9.332000e+03,9332,9332.000000,9332,9332,9331.000000,9.332000e+03,9332,9332
unique,2,NaN,9332,9332,NaN,NaN,NaN,9332,NaN,10,...,2,NaN,7807,NaN,5,42,NaN,NaN,9332,110
top,green,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ci37389218,",NaN,ml,...,reviewed,NaN,"M 0.4 - 10km NE of Aguanga, CA",NaN,earthquake,",geoserve,origin,phase-data,",NaN,NaN,https://earthquake.usgs.gov/earthquakes/eventp...,Alaska
freq,58,NaN,1,1,NaN,NaN,NaN,1,NaN,6803,...,7797,NaN,55,NaN,9081,5301,NaN,NaN,1,3665
mean,NaN,2.754711,NaN,NaN,0.544925,12.310030,121.506588,NaN,1.497345,NaN,...,NaN,1.538284e+12,NaN,0.006537,NaN,NaN,-451.990140,1.538537e+12,NaN,NaN
std,NaN,1.010637,NaN,NaN,2.214305,48.954944,72.962363,NaN,1.203347,NaN,...,NaN,6.080306e+08,NaN,0.080589,NaN,NaN,231.752571,6.564135e+08,NaN,NaN
min,NaN,0.000000,NaN,NaN,0.000648,0.000000,12.000000,NaN,-1.260000,NaN,...,NaN,1.537229e+12,NaN,0.000000,NaN,NaN,-720.000000,1.537230e+12,NaN,NaN
25%,NaN,2.000000,NaN,NaN,0.020425,1.000000,66.142500,NaN,0.720000,NaN,...,NaN,1.537793e+12,NaN,0.000000,NaN,NaN,-540.000000,1.537996e+12,NaN,NaN
50%,NaN,2.700000,NaN,NaN,0.059050,2.000000,105.000000,NaN,1.300000,NaN,...,NaN,1.538245e+12,NaN,0.000000,NaN,NaN,-480.000000,1.538621e+12,NaN,NaN
75%,NaN,3.300000,NaN,NaN,0.177250,5.000000,159.000000,NaN,1.900000,NaN,...,NaN,1.538766e+12,NaN,0.000000,NaN,NaN,-480.000000,1.539110e+12,NaN,NaN
max,NaN,8.400000,NaN,NaN,53.737000,580.000000,355.910000,NaN,7.500000,NaN,...,NaN,1.539475e+12,NaN,1.000000,NaN,NaN,720.000000,1.539537e+12,NaN,NaN

1. Find the 95th percentile of earthquake magnitude in Japan using the mb magnitude type.

In [61]:
df[df['parsed_place'] == 'Japan']['mag'].quantile(0.95)

5.119999999999999

2. Find the percentage of earthquakes in Indonesia that were coupled with tsunamis.

In [62]:
indo = df[(df['parsed_place'] == 'Indonesia')]
indo_tsu = df[(df['parsed_place'] == 'Indonesia') & (df['tsunami'] == 1)]

percent_indo_tsu = indo_tsu.parsed_place.count() / indo.parsed_place.count() 
round(percent_indo_tsu, 2)

0.23

3. Calculate summary statistics for earthquakes in Nevada.

In [63]:
df[df['parsed_place'] == 'Nevada'].describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,681.000000,15.000000,681.000000,681.000000,1.00,681.000000,681.000000,681.000000,6.810000e+02,681.0,681.0,6.810000e+02
mean,2.440000,0.166199,2.400000,153.668120,0.500073,2.84,12.618209,0.151986,10.970631,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166228,4.626013,68.735302,0.696710,NaN,9.866963,0.084662,19.607150,5.965637e+08,0.0,0.0,6.010951e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.053000,1.000000,97.380000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.112000,1.000000,149.140000,0.400000,2.84,10.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.233000,1.000000,199.720000,0.900000,2.84,16.000000,0.187100,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

4. Add a column indicating whether the earthquake happened in a country or US state that is on the Ring of Fire. Use Alaska, Antarctica (look for Antarctic), Bolivia, California, Canada, Chile, Costa Rica, Ecuador, Fiji, Guatemala, Indonesia, Japan, Kermadec Islands, Mexico (be careful not to select New Mexico), New Zealand, Peru, Philippines, Russia, Taiwan, Tonga, and Washington.

In [66]:
us_mask = df['parsed_place'].isin(['Alaska', 'California', 'Washington'])
ring_mask = df['parsed_place'].isin(['Antarctica', 'Bolivia', 'Canada', 'Chile', 'Costa Rica', 'Ecuador', 'Fiji', 'Guatemala', 'Indonesia', 'Japan', 'Kermadec Islands', 'Mexico', 'New Zealand', 'Peru', 'Philippines', 'Russia', 'Taiwan', 'Tonga'])
df = df.assign(
    region=np.where(
        us_mask,
        'US',
        np.where(ring_mask, 'Ring of Fire', 'Other')
    )
)
df.head(2)

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,time,title,tsunami,type,types,tz,updated,url,parsed_place,region
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California,US
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California,US

5. Calculate the number of earthquakes in the Ring of Fire locations and the number outside of them.

In [78]:
earthquakes_by_region = df.groupby('region').size().reset_index(name='count')
earthquakes_in_us = earthquakes_by_region[earthquakes_by_region['region'] == 'US']['count'].iloc[0]
earthquakes_elsewhere = earthquakes_by_region[earthquakes_by_region['region'] != 'US']['count'].sum()
earthquakes_in_us, earthquakes_elsewhere

(6683, 2649)

6. Find the tsunami count along the Ring of Fire.

In [85]:
df[df['region'] == 'Ring of Fire']['tsunami'].sum()

39